services:
  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway/src:/usr/src/app/src
    command: yarn start:dev
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    environment:
      - PORT=3000
  users-microservice:
    build:
      context: .
      dockerfile: ./users/Dockerfile
    volumes:
      - ./users/src:/usr/src/app/src
    command: yarn start:dev
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    environment:
      - MONGODB_URI=mongodb://root:password123@mongodb-primary:27017/
  mailer-microservice:
    build:
      context: .
      dockerfile: ./mailer/Dockerfile
    volumes:
        - ./mailer/src:/usr/src/app/src
    command: yarn start:dev
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    environment:
      - MAIL_PORT=465
      - MAIL_HOST=gmail
      - MAIL_USER=stanislavkravchenko17@gmail.command
      - MAIL_PASS=feyr pvjq trqj srwm 
      - APP_NAME=Travel-Ease
  nats:
    image: nats
    ports:
      - 4222:4222
  mongodb-primary:
    image: docker.io/bitnami/mongodb:7.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:7.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:7.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local
  
  